"""update enum

Revision ID: f3e1727ed2a7
Revises: 9af66683f3e4
Create Date: 2024-01-25 12:54:32.468389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f3e1727ed2a7"
down_revision = "9af66683f3e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
