"""add rental unit

Revision ID: 9af66683f3e4
Revises: b460d0104381
Create Date: 2024-01-25 12:35:43.363754

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9af66683f3e4"
down_revision = "b460d0104381"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("street", sa.VARCHAR(length=255), nullable=True),
        sa.Column("postal_code", sa.VARCHAR(length=10), nullable=True),
        sa.Column("city", sa.VARCHAR(length=255), nullable=True),
        sa.Column("state", sa.VARCHAR(length=255), nullable=True),
        sa.Column("country", sa.VARCHAR(length=2), nullable=True),
        sa.Column("lat", sa.FLOAT(asdecimal=True), nullable=True),
        sa.Column("lng", sa.FLOAT(asdecimal=True), nullable=True),
        sa.CheckConstraint("octet_length(id) <= 40", name="id_byte_limit"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rental_unit",
        sa.Column("id", sa.String(length=63), nullable=False),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column(
            "permission",
            postgresql.ENUM("IS_ADMIN", "IS_HOST", name="permissionenum"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "id ~* '^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?$'",
            name="id_format_check",
        ),
        sa.ForeignKeyConstraint(
            ["address"],
            ["addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id", "organization_id"),
        sa.UniqueConstraint("external_id", "organization_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rental_unit")
    op.drop_table("addresses")
    # ### end Alembic commands ###
