"""posts

Revision ID: 7b5cd0059bf4
Revises: 85fa1ab2cee4
Create Date: 2024-02-28 12:37:18.094104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b5cd0059bf4"
down_revision = "85fa1ab2cee4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
