"""post relationship in user table

Revision ID: 432505655f57
Revises: e473554f51ac
Create Date: 2024-02-28 15:21:39.034694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "432505655f57"
down_revision = "e473554f51ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
