"""USER TOKEN

Revision ID: 0623ff7309a5
Revises: d092ed421e62
Create Date: 2024-02-29 15:28:06.349393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0623ff7309a5"
down_revision = "d092ed421e62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
