"""post and user table

Revision ID: 49896241fc65
Revises: c78d4ef96e24
Create Date: 2024-02-28 16:04:48.584875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "49896241fc65"
down_revision = "c78d4ef96e24"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
