"""UUID

Revision ID: 08d694c6069c
Revises: 414c024134ca
Create Date: 2024-03-05 19:04:09.988019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08d694c6069c"
down_revision = "414c024134ca"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "post",
        "id",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('post_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "post",
        "id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
        autoincrement=True,
        existing_server_default=sa.text("nextval('post_id_seq'::regclass)"),
    )
    # ### end Alembic commands ###
