"""post and user table

Revision ID: 245da5d73b0a
Revises: 4a912cad670e
Create Date: 2024-02-28 15:50:41.466513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "245da5d73b0a"
down_revision = "4a912cad670e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
