"""UUID

Revision ID: 414c024134ca
Revises: addf0063970e
Create Date: 2024-03-05 18:58:59.198831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "414c024134ca"
down_revision = "addf0063970e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
