"""post and user table

Revision ID: 4a912cad670e
Revises: fb68a27713e7
Create Date: 2024-02-28 15:48:19.776101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4a912cad670e"
down_revision = "fb68a27713e7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
