"""post and user table

Revision ID: c78d4ef96e24
Revises: 245da5d73b0a
Create Date: 2024-02-28 15:51:38.281047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c78d4ef96e24"
down_revision = "245da5d73b0a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
