"""post relationship in user table

Revision ID: e473554f51ac
Revises: 7b5cd0059bf4
Create Date: 2024-02-28 15:18:50.797155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e473554f51ac"
down_revision = "7b5cd0059bf4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
