"""UUID

Revision ID: addf0063970e
Revises: 0623ff7309a5
Create Date: 2024-03-05 18:57:33.433532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "addf0063970e"
down_revision = "0623ff7309a5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "post",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "post",
        "id",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
